import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("com.android.application")
    // Kotlin itself comes from AGP's built-in Kotlin support (AGP 9), so
    // org.jetbrains.kotlin.android is deliberately not applied.
    id("org.jetbrains.kotlin.plugin.compose")
}

android {
    namespace = "org.circa.clock"
    // androidx.wear.compose 1.7.0 (latest stable) requires compileSdk 37; targetSdk stays 36.
    compileSdk = 37

    defaultConfig {
        applicationId = "org.circa.clock"
        minSdk = 34
        targetSdk = 36
        versionCode = 1
        versionName = "0.1"
    }

    buildTypes {
        release {
            // Signing is done by build-all.sh with the AOSP platform testkey,
            // so Gradle leaves this build unsigned.
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
    }

    // One copy of the Material Symbols (Rounded) ImageVectors, shared by every Circa Compose app.
    // Generated by tools/gen-symbols.py (tools/symbols/names.txt); see shared/symbols.
    sourceSets {
        getByName("main") {
            kotlin.srcDir(rootProject.file("../shared/symbols/src/main/kotlin"))
        }
    }
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_17
    }
}

dependencies {
    implementation("androidx.activity:activity-compose:1.13.0")
    implementation("androidx.wear.compose:compose-material3:1.7.0")
    implementation("androidx.wear.compose:compose-foundation:1.7.0")

    testImplementation("junit:junit:4.13.2")
}
