#!/usr/bin/env python3
"""Generate Circa's vendored Material Symbols (Rounded) sources.

Every Circa UI uses Material Symbols (Rounded) - the set stock Wear OS ships - and no emoji or
Unicode-as-icon. This script is the single source of truth for that set. It is run by hand and its
output is committed; it never runs at build time.

Input
-----
tools/symbols/names.txt - one "<name> [target ...]" per line (see the file's header). <name> is a
Material Symbols name from github.com/google/material-design-icons. Both the filled
(<name>_fill1_24px.svg) and outlined (<name>_24px.svg) SVGs are downloaded from the
`symbols/web/<name>/materialsymbolsrounded/` directory.

Downloads are cached under .cache/symbols/ (git-ignored), so a re-run works offline.

Output
------
(a) shared/symbols/src/main/kotlin/org/circa/symbols/CircaSymbols.kt
    ONE Kotlin file of ImageVectors, shared by launcher, settings, clock and companion (each app adds
    this source dir to its `main` source set). `CircaSymbols.Filled.<Name>` / `CircaSymbols.Outlined.<Name>`.
(b) <SystemUI>/res/drawable/circa_ic_<name>.xml      for names marked `sysui`, only with --systemui-dir
    (frameworks/base/packages/SystemUI/res/drawable in a Circa source tree)
    (the QS-tile pipeline needs an android.graphics.drawable.Drawable, not a Compose ImageVector).
(c) keyboard/.../res/drawable/circa_ic_<name>{,_outlined}.xml  for names marked `keyboard`
    (the keyboard is a bare android.view.View with no AndroidX, so it draws platform VectorDrawables).
(d) watchlink/.../res/drawable/circa_ic_<name>.xml   for names marked `watchlink`   (filled)
    (WatchLink posts platform notifications, whose small icon must be a resource id, not a Compose ImageVector).

Usage:  tools/gen-symbols.py [--systemui-dir DIR]
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]   # the apps root (shared/, keyboard/, tools/)
NAMES_FILE = ROOT / "tools/symbols/names.txt"
CACHE_DIR = ROOT / ".cache/symbols"
SHARED_OUT = ROOT / "shared/symbols/src/main/kotlin/org/circa/symbols/CircaSymbols.kt"
KEYBOARD_DRAWABLE_DIR = ROOT / "keyboard/app/src/main/res/drawable"
WATCHLINK_DRAWABLE_DIR = ROOT / "watchlink/app/src/main/res/drawable"

RAW = (
    "https://raw.githubusercontent.com/google/material-design-icons/master/"
    "symbols/web/{name}/materialsymbolsrounded/{file}"
)
UA = "circa-gen-symbols/1.0"
VARIANTS = {"filled": "{name}_fill1_24px.svg", "outlined": "{name}_24px.svg"}


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def parse_names(path: Path) -> list[tuple[str, set[str]]]:
    entries: list[tuple[str, set[str]]] = []
    seen: set[str] = set()
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        name, targets = parts[0], set(parts[1:])
        bad = targets - {"sysui", "keyboard", "watchlink"}
        if bad:
            sys.exit(f"{path}:{lineno}: unknown target(s): {' '.join(sorted(bad))}")
        if not re.fullmatch(r"[a-z0-9_]+", name):
            sys.exit(f"{path}:{lineno}: bad symbol name: {name!r}")
        if name in seen:
            sys.exit(f"{path}:{lineno}: duplicate symbol name: {name}")
        seen.add(name)
        entries.append((name, targets))
    if not entries:
        sys.exit(f"{path}: no symbol names")
    return entries


def fetch(name: str, variant: str) -> str:
    """Return the (cached or downloaded) SVG text for <name>_<variant>."""
    cache = CACHE_DIR / f"{name}.{variant}.svg"
    if cache.exists():
        return cache.read_text()
    url = RAW.format(name=name, file=VARIANTS[variant].format(name=name))
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        svg = resp.read().decode("utf-8")
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(svg)
    print(f"fetched {name}:{variant}")
    return svg


def path_data(svg: str, name: str, variant: str) -> str:
    match = re.search(r"<path\b[^>]*\bd=\"([^\"]+)\"", svg)
    if not match:
        sys.exit(f"{name}:{variant}: no <path d=...> in the SVG")
    return match.group(1)


def load_paths(entries: list[tuple[str, set[str]]]) -> dict[str, dict[str, str]]:
    paths: dict[str, dict[str, str]] = {}
    for name, _ in entries:
        paths[name] = {
            variant: path_data(fetch(name, variant), name, variant)
            for variant in VARIANTS
        }
    return paths


# --- outputs -------------------------------------------------------------------------------------------


def write_shared(entries: list[tuple[str, set[str]]], paths: dict[str, dict[str, str]]) -> None:
    lines = [
        "// Generated by tools/gen-symbols.py from tools/symbols/names.txt - do not edit by hand.",
        "package org.circa.symbols",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.graphics.SolidColor",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import androidx.compose.ui.graphics.vector.PathParser",
        "import androidx.compose.ui.unit.dp",
        "",
        "/**",
        " * Material Symbols (Rounded, 24 px) - the icon set stock Wear OS and Pixel phones use, so every",
        " * Circa surface reads at a glance. Apache License 2.0, (c) Google; paths vendored from",
        " * github.com/google/material-design-icons `symbols/web/<name>/materialsymbolsrounded/`:",
        " * `<name>_fill1_24px.svg` ([Filled]) and `<name>_24px.svg` ([Outlined]), viewBox",
        ' * "0 -960 960 960". Drawn black and tinted by `Icon`, the way the material-icons artifacts do.',
        " *",
        " * Shared by launcher, settings, clock and companion (apps/shared/symbols is added to each app's",
        " * `main` source set), so there is exactly one copy of every glyph.",
        " */",
        "internal object CircaSymbols {",
        "    /** FILL=1. */",
        "    internal object Filled {",
    ]
    for name, _ in entries:
        lines.append(f"        /** `{name}` */")
        lines.append(
            f'        val {pascal(name)}: ImageVector by lazy '
            f'{{ symbol("{name}", "{paths[name]["filled"]}") }}'
        )
    lines += ["    }", "", "    /** FILL=0. */", "    internal object Outlined {"]
    for name, _ in entries:
        lines.append(f"        /** `{name}` */")
        lines.append(
            f'        val {pascal(name)}: ImageVector by lazy '
            f'{{ symbol("{name}", "{paths[name]["outlined"]}") }}'
        )
    lines += [
        "    }",
        "}",
        "",
        '/** Builds a Material Symbols vector: the path data uses a "0 -960 960 960" viewBox, so shift it down. */',
        "private fun symbol(name: String, pathData: String): ImageVector =",
        "    ImageVector.Builder(",
        "        name = name,",
        "        defaultWidth = 24.dp,",
        "        defaultHeight = 24.dp,",
        "        viewportWidth = 960f,",
        "        viewportHeight = 960f,",
        "    ).apply {",
        "        addGroup(translationY = 960f)",
        "        addPath(",
        "            pathData = PathParser().parsePathString(pathData).toNodes(),",
        "            fill = SolidColor(Color.Black),",
        "        )",
        "        clearGroup()",
        "    }.build()",
        "",
    ]
    SHARED_OUT.parent.mkdir(parents=True, exist_ok=True)
    SHARED_OUT.write_text("\n".join(lines))
    print(f"wrote {SHARED_OUT.relative_to(ROOT)}")


def drawable_xml(name: str, outlined: bool, tinted: bool, path: str) -> str:
    variant = "outlined" if outlined else "filled"
    tint = '\n    android:tint="?android:attr/colorControlNormal"' if tinted else ""
    fill = "@android:color/white" if tinted else "#FFFFFFFF"
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- Material Symbols Rounded "{name}" ({variant}), Apache License 2.0, (c) Google. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp"\n'
        '    android:height="24dp"\n'
        '    android:viewportWidth="960"\n'
        '    android:viewportHeight="960"'
        f"{tint}>\n"
        '    <group android:translateY="960">\n'
        "        <path\n"
        f'            android:fillColor="{fill}"\n'
        f'            android:pathData="{path}" />\n'
        "    </group>\n"
        "</vector>\n"
    )


def write_drawables(
    names: list[str],
    paths: dict[str, dict[str, str]],
    out_dir: Path,
    outlined_too: bool,
    tinted: bool,
) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in names:
        (out_dir / f"circa_ic_{name}.xml").write_text(
            drawable_xml(name, outlined=False, tinted=tinted, path=paths[name]["filled"])
        )
        if outlined_too:
            (out_dir / f"circa_ic_{name}_outlined.xml").write_text(
                drawable_xml(name, outlined=True, tinted=False, path=paths[name]["outlined"])
            )
    print(f"wrote {len(names)} drawable(s) to {out_dir}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "--systemui-dir",
        type=Path,
        default=None,
        help="SystemUI res/drawable dir; the `sysui` drawables are only written when it is given",
    )
    args = ap.parse_args()

    entries = parse_names(NAMES_FILE)
    paths = load_paths(entries)
    write_shared(entries, paths)
    if args.systemui_dir is not None:
        write_drawables(
            [n for n, t in entries if "sysui" in t],
            paths,
            args.systemui_dir,
            outlined_too=False,
            tinted=True,
        )
    else:
        print("no --systemui-dir: SystemUI drawables not written")
    write_drawables(
        [n for n, t in entries if "keyboard" in t],
        paths,
        KEYBOARD_DRAWABLE_DIR,
        outlined_too=True,
        tinted=False,
    )
    write_drawables(
        [n for n, t in entries if "watchlink" in t],
        paths,
        WATCHLINK_DRAWABLE_DIR,
        outlined_too=False,
        tinted=False,
    )


if __name__ == "__main__":
    main()
