#!/usr/bin/env bash
# Write <dir>/Android.bp (one android_app_import per Circa APK present in <dir>) and <dir>/packages.mk (their
# PRODUCT_PACKAGES), for circa-apps.mk. Called by build-all.sh; only APKs that exist get a module, because a
# module whose APK is missing breaks every build of the tree.
set -euo pipefail
D="${1:?usage: gen-prebuilt-bp.sh <prebuilt dir>}"
BP="$D/Android.bp"
MK="$D/packages.mk"

wear_libs='    optional_uses_libs: [
        "wear-sdk",
        "androidx.window.extensions",
        "androidx.window.sidecar",
    ],'

# module | comment | extra properties (Soong syntax, 4-space indented)
mod() {
  local m=$1 comment=$2 extra=$3
  [ -f "$D/$m.apk" ] || return 0
  cat >>"$BP" <<BP

// $comment
android_app_import {
    name: "$m",
    apk: "$m.apk",
    preprocessed: true,
    presigned: true,
    privileged: true,
    product_specific: true,
$extra
}
BP
  echo "PRODUCT_PACKAGES += $m" >>"$MK"
}

cat >"$BP" <<'BP'
// GENERATED by build-all.sh (tools/gen-prebuilt-bp.sh) - do not edit. The Circa apps as prebuilt priv-apps on
// /product, signed by build-all.sh (preprocessed: aligned, dex stored uncompressed). The configuration they
// `require` (privapp/default permissions, sysconfig, the launcher overlay) lives in device/circa/apps.
BP
echo "# GENERATED by build-all.sh - do not edit." >"$MK"

mod CircaLauncher "Watch face / home launcher (org.circa.launcher). Our launcher is the only HOME: no Launcher3." "$wear_libs
    overrides: [
        \"Launcher3QuickStep\",
        \"Launcher3Overlay\",
    ],
    required: [
        \"CircaLauncherOverlay\",
        \"privapp-permissions-circa.xml\",
        \"default-permissions-circa.xml\",
    ],"
mod WatchLink "Phone link for Gadgetbridge (org.circa.watchlink). AOSP testkey, not the platform key." "    required: [
        \"privapp-permissions-circa.xml\",
        \"default-permissions-circa.xml\",
        \"sysconfig-circa.xml\",
    ],"
mod CircaSettings "Round Settings (org.circa.settings). AOSP Settings stays installed as the backend." "$wear_libs
    required: [
        \"privapp-permissions-circa.xml\",
        \"default-permissions-circa.xml\",
        \"sysconfig-circa-settings.xml\",
    ],"
mod CircaKeyboard "Watch keyboard (org.circa.keyboard), the only system IME. No <uses-library> tags in its manifest." "    overrides: [\"LatinIME\"],
    required: [
        \"privapp-permissions-circa.xml\",
        \"default-permissions-circa.xml\",
    ],"
mod CircaClock "Round Clock (org.circa.clock): alarms, timers, stopwatch; replaces DeskClock." "$wear_libs
    overrides: [\"DeskClock\"],
    required: [
        \"privapp-permissions-circa.xml\",
        \"default-permissions-circa.xml\",
    ],"
mod CircaCompanion "Circa Companion (org.circa.companion): Media, Weather, Agenda, Find phone, Flashlight." "$wear_libs"
mod CircaExercise "Round Exercise (org.circa.exercise): workout tracking (side button long press)." "$wear_libs
    required: [
        \"privapp-permissions-circa.xml\",
        \"default-permissions-circa.xml\",
    ],"
echo "wrote $BP and $MK ($(grep -c '^PRODUCT_PACKAGES' "$MK") modules)"
